"""Initial migration

Revision ID: d9e92720e17b
Revises: 
Create Date: 2024-06-24 01:56:22.572401

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd9e92720e17b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('qn_a',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('incoming_file_url', sa.String(length=255), nullable=False),
    sa.Column('incoming_file_gsc_uri', sa.String(length=255), nullable=False),
    sa.Column('outgoing_file_url', sa.String(length=255), nullable=True),
    sa.Column('incoming_text', sa.Text(), nullable=True),
    sa.Column('outgoing_text', sa.Text(), nullable=True),
    sa.Column('state', sa.Enum('AUDIO_RECEIVED', 'TRANSCRIBING', 'FETCHING_ANSWER', 'SPEECH_SYNTHESIS', 'ANSWER_READY', 'FAILED', name='qnastates'), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('incoming_file_gsc_uri'),
    sa.UniqueConstraint('incoming_file_url'),
    sa.UniqueConstraint('outgoing_file_url')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('qn_a')
    # ### end Alembic commands ###
